const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    CREATE_ONE_VIDEO: 'CREATE_ONE_VIDEO',
    GET_ALL_VIDEO: 'GET_ALL_VIDEO',
    UPDATE_ONE_VIDEO: 'UPDATE_ONE_VIDEO',
    DELETE_ONE_VIDEO: 'DELETE_ONE_VIDEO',
    GET_ONE_VIDEO_MYTHOLOGY: 'GET_ONE_VIDEO_MYTHOLOGY',
    GET_ONE_VIDEO_ID: 'GET_ONE_VIDEO_ID',
    GET_ONE_VIDEO_FAMILY: 'GET_ONE_VIDEO_FAMILY',
    USER_LOGOUT: 'USER_LOGOUT',
    GET_ALL_VIDEO_BY_TIME: 'GET_ALL_VIDEO_BY_TIME',
    SEARCH_KEY: 'SEARCH_KEY',
    SEARCH_MENU: 'SEARCH_MENU'






})

export default actionTypes;